name: Netlify -> Algolia Crawler
on:
  push:
    branches: [master]

jobs:
  algolia_recrawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2

      # We don't know when the site will be deployed, we just wait a few seconds
      # Better solutions can be found
      - name: Sleep for 30s
        run: sleep 30

      # For master branch
      - name: Netlify-MASTER => Algolia crawler creation and recrawl (Push on Master branch)
        uses: algolia/algoliasearch-crawler-github-actions@v1
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://gostd.impossible98.win/'
          override-config: true
